version: 2

aliases:
  - &cargo_components
    run:
      name: Install cargo components
      command: |
        export PATH=/root/.cargo/bin:$PATH
        rustup component add rustfmt
  - &cargo_build
    run:
      name: Cargo build
      command: |
        export PATH=/root/.cargo/bin:$PATH
        cargo build -vv
  - &cargo_test
    run:
      name: Cargo test
      command: |
        export PATH=/root/.cargo/bin:$PATH
        cargo test -v
  - &cargo_fmt
    run:
      name: Cargo fmt
      command: |
        export PATH=/root/.cargo/bin:$PATH
        cargo fmt -v

.job_apt_template: &job_apt
  steps:
    - checkout
    - run:
        name: Install Rust
        command: |
          apt update
          apt install -y curl
          apt install -y clang-6.0
          curl https://sh.rustup.rs -sSf | sh -s -- -y
    - *cargo_components
    - *cargo_build
    - *cargo_test
    - *cargo_fmt

.job_yum_template: &job_yum
  steps:
    - checkout
    - run:
        name: Install Rust
        command: |
          yum install -y curl
          yum install clang clang-devel  
          curl https://sh.rustup.rs -sSf | sh -s -- -y
    - *cargo_components
    - *cargo_build
    - *cargo_test
    - *cargo_fmt

jobs:
  latest:
    <<: *job_apt
    docker:
      - image: nvidia/cuda:latest
  9.2-devel-ubuntu18.04:
    <<: *job_apt
    docker:
      - image: nvidia/cuda:9.2-devel-ubuntu18.04
  10.0-devel-ubuntu16.04:
    <<: *job_apt
    docker:
      - image: nvidia/cuda:10.0-devel-ubuntu16.04
  9.2-devel-ubuntu16.04:
    <<: *job_apt
    docker:
      - image: nvidia/cuda:9.2-devel-ubuntu16.04
  9.1-devel-ubuntu16.04:
    <<: *job_apt
    docker:
      - image: nvidia/cuda:9.1-devel-ubuntu16.04
  9.0-devel-ubuntu16.04:
    <<: *job_apt
    docker:
      - image: nvidia/cuda:9.0-devel-ubuntu16.04
  8.0-devel-ubuntu16.04:
    <<: *job_apt
    docker:
      - image: nvidia/cuda:8.0-devel-ubuntu16.04
  8.0-devel-ubuntu14.04:
    <<: *job_apt
    docker:
      - image: nvidia/cuda:8.0-devel-ubuntu14.04
  7.5-devel-ubuntu14.04:
    <<: *job_apt
    docker:
      - image: nvidia/cuda:7.5-devel-ubuntu14.04
  7.0-devel-ubuntu14.04:
    <<: *job_apt
    docker:
      - image: nvidia/cuda:7.0-devel-ubuntu14.04
  6.5-devel-ubuntu14.04:
    <<: *job_apt
    docker:
      - image: nvidia/cuda:6.5-devel-ubuntu14.04
  10.0-devel-centos7:
    <<: *job_yum
    docker:
      - image: nvidia/cuda:10.0-devel-centos7
  9.2-devel-centos7:
    <<: *job_yum
    docker:
      - image: nvidia/cuda:9.2-devel-centos7
  9.1-devel-centos7:
    <<: *job_yum
    docker:
      - image: nvidia/cuda:9.1-devel-centos7
  9.0-devel-centos7:
    <<: *job_yum
    docker:
      - image: nvidia/cuda:9.0-devel-centos7
  8.0-devel-centos7:
    <<: *job_yum
    docker:
      - image: nvidia/cuda:8.0-devel-centos7
  7.5-devel-centos7:
    <<: *job_yum
    docker:
      - image: nvidia/cuda:7.5-devel-centos7
  7.0-devel-centos7:
    <<: *job_yum
    docker:
      - image: nvidia/cuda:7.0-devel-centos7

workflows:
  version: 2
  tests:
    jobs:
      - latest
      - 9.2-devel-ubuntu18.04
      - 10.0-devel-ubuntu16.04
      # - 9.2-devel-ubuntu16.04
      # - 9.1-devel-ubuntu16.04
      # - 9.0-devel-ubuntu16.04
      # - 8.0-devel-ubuntu16.04
      # - 8.0-devel-ubuntu14.04
      # - 7.5-devel-ubuntu14.04
      # - 7.0-devel-ubuntu14.04
      # - 6.5-devel-ubuntu14.04
      - 10.0-devel-centos7
      # - 9.2-devel-centos7
      # - 9.1-devel-centos7
      # - 9.0-devel-centos7
      # - 8.0-devel-centos7
      # - 7.5-devel-centos7
      # - 7.0-devel-centos7
